[project]
name = "linguamate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lark-oapi>=1.4.10",
    "litellm>=1.61.15",
    "loguru>=0.7.3",
    "pymongo>=4.11.1",
    "python-dotenv>=1.0.1",
]
